# Generated by Django 4.2.4 on 2024-03-07 15:06

from django.db import migrations, models
import ond_eventos.models.ondevento


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cidade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uf",
                    models.CharField(
                        choices=[
                            ("AC", "Acre"),
                            ("AL", "Alagoas"),
                            ("AP", "Amapá"),
                            ("AM", "Amazonas"),
                            ("BA", "Bahia"),
                            ("CE", "Ceará"),
                            ("ES", "Espírito Santo"),
                            ("GO", "Goiás"),
                            ("MA", "Maranhão"),
                            ("MT", "Mato Grosso"),
                            ("MS", "Mato Grosso do Sul"),
                            ("MG", "Minas Gerais"),
                            ("PA", "Pará"),
                            ("PB", "Paraíba"),
                            ("PR", "Paraná"),
                            ("PE", "Pernabuco"),
                            ("PI", "Piauí"),
                            ("RJ", "Rio de Janeiro"),
                            ("RN", "Rio Grande do Norte"),
                            ("RS", "Rio Grande do Sul"),
                            ("RO", "Rondônia"),
                            ("RR", "Roraima"),
                            ("SC", "Santa Catarina"),
                            ("SP", "São Paulo"),
                            ("SE", "Sergipe"),
                            ("TO", "Tocantins"),
                            ("DF", "Distrito Federal"),
                        ],
                        max_length=2,
                        verbose_name="Unidade da Federação",
                    ),
                ),
                ("nome", models.TextField(db_index=True, max_length=100)),
                ("fuso", models.TextField(default="America/Sao_Paulo", max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="OndEvento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.TextField(max_length=100, verbose_name="nome do evento"),
                ),
                (
                    "capa",
                    models.ImageField(
                        null=True,
                        upload_to=ond_eventos.models.ondevento._foto_capa_upload,
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("FEST", "Festa"),
                            ("BAR", "Bar"),
                            ("ROLE", "Rolê de Rua"),
                            ("BLOQ", "Bloquinho"),
                            ("SHOW", "Show"),
                            ("ANIV", "Aniversário"),
                            ("FORM", "Formatura"),
                            ("CASA", "Casamento"),
                            ("CULT", "Evento Cultural"),
                            ("FEIR", "Feira"),
                            ("OUTR", "Outro"),
                        ],
                        max_length=4,
                        verbose_name="tipo de evento",
                    ),
                ),
                ("inicio", models.DateTimeField(verbose_name="início do evento")),
                ("fim", models.DateTimeField(verbose_name="fim do evento")),
                (
                    "descricao",
                    models.TextField(max_length=120, verbose_name="Descrição"),
                ),
                ("endereco", models.TextField(max_length=200, null=True)),
            ],
        ),
    ]
