# Generated by Django 4.2.4 on 2024-03-07 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("ond_eventos", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="ondevento",
            name="autor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="eventos_criados",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="ondevento",
            name="cidade",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="eventos_da_cidade",
                to="ond_eventos.cidade",
            ),
        ),
        migrations.AddConstraint(
            model_name="ondevento",
            constraint=models.CheckConstraint(
                check=models.Q(("fim__gte", models.F("inicio"))),
                name="fim_depois_do_inicio",
                violation_error_message="Data de início depois da de fim",
            ),
        ),
    ]
