# Generated by Django 4.2.4 on 2024-03-07 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="AtividadeModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "acao_nome",
                    models.TextField(
                        choices=[
                            ("COMENTOU", "Comentou"),
                            ("SEGUIU", "Seguiu"),
                            ("CONVIDOU", "Convidou"),
                        ],
                        max_length=10,
                    ),
                ),
                ("acao_id", models.PositiveIntegerField()),
                ("alvo_id", models.PositiveIntegerField()),
                ("visto", models.BooleanField(default=False)),
                ("criacao", models.DateTimeField(auto_now=True)),
                ("alteracao", models.DateTimeField(auto_now_add=True)),
                ("deletado", models.BooleanField(default=False)),
                (
                    "acao_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="atividade_acao",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "alvo_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="atividade_alvo",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
        ),
    ]
