# Generated by Django 4.2.4 on 2024-03-07 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("ond_notificacao", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="atividademodel",
            name="ator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="atividades",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="atividademodel",
            name="notificar_para",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="minhas_notificacoes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="atividademodel",
            index=models.Index(
                fields=["notificar_para", "visto"],
                name="ond_notific_notific_b19126_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="atividademodel",
            index=models.Index(
                fields=["id", "notificar_para"], name="ond_notific_id_fcdae0_idx"
            ),
        ),
    ]
