from .menu_principal_perfil import menu_principal_perfil_view
from .meus_eventos import meus_eventos_view
from .minhas_confirmacoes_presenca import minhas_confirmacoes_de_presenca_view
from .meus_convites import meus_convites_view
from .perfil import perfil_view
from .editar_perfil import editar_perfil_view
from .login import login_view
from .criar_conta import criar_conta_view
from .logout import logout_view
