# Generated by Django 4.2.4 on 2024-03-07 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("ond_eventos", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Comentario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("corpo", models.TextField(max_length=120)),
                ("momento", models.DateTimeField(auto_now=True)),
                ("alteracao", models.DateTimeField(auto_now_add=True)),
                ("deletado", models.BooleanField(default=False)),
                (
                    "do_autor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="comentarios_realizados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "no_evento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comentarios_do_evento",
                        to="ond_eventos.ondevento",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RespostaComentario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("corpo", models.TextField(max_length=120)),
                ("momento", models.DateTimeField(auto_now=True)),
                (
                    "do_autor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="respostas_dadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "para",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="respostas_do_comentario",
                        to="ond_social.comentario",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReacaoRespostaComentarioModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("LIKE", "Like"), ("UTIL", "Util")], max_length=4
                    ),
                ),
                ("momento", models.DateTimeField(auto_now=True)),
                (
                    "resposta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="reacoes_da_resposta_comentario",
                        to="ond_social.respostacomentario",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="minhas_reacoes_resposta_comentario",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "reacao_resposta_comentario",
            },
        ),
        migrations.CreateModel(
            name="ReacaoComentarioModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("LIKE", "Like"), ("UTIL", "Util")], max_length=4
                    ),
                ),
                ("momento", models.DateTimeField(auto_now=True)),
                (
                    "comentario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="reacoes_do_comentario",
                        to="ond_social.comentario",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="minhas_reacoes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "reacao_comentario",
            },
        ),
        migrations.CreateModel(
            name="ConviteOndEvento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("momento", models.DateTimeField(auto_now=True)),
                (
                    "de",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="convite_enviado",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "evento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="convidados",
                        to="ond_eventos.ondevento",
                    ),
                ),
                (
                    "para",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="convite_recebido",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ConfirmacaoPresenca",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("momento", models.DateTimeField(auto_now=True)),
                (
                    "do_usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="confirmacoes_de_presenca",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "no_evento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="confirmados_no_evento",
                        to="ond_eventos.ondevento",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RelacaoModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("SEG", "Seguindo"), ("BLQ", "Bloqueado")],
                        max_length=3,
                    ),
                ),
                ("criacao", models.DateTimeField(auto_now=True)),
                ("alteracao", models.DateTimeField(auto_now_add=True)),
                (
                    "com",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relacao_recebida",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "de",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relacao_emitida",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [models.Index(fields=["de", "com"], name="de_com_indice")],
            },
        ),
        migrations.AddConstraint(
            model_name="relacaomodel",
            constraint=models.UniqueConstraint(
                fields=("de", "com"), name="unico_relacionamento"
            ),
        ),
        migrations.AddIndex(
            model_name="reacaorespostacomentariomodel",
            index=models.Index(
                fields=["usuario", "resposta"], name="reacao_resp_usuario_a9ffe8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reacaocomentariomodel",
            index=models.Index(
                fields=["usuario", "comentario"], name="reacao_come_usuario_65998d_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="confirmacaopresenca",
            constraint=models.UniqueConstraint(
                fields=("do_usuario", "no_evento"),
                name="unica_confirmacao_usuario_evento",
            ),
        ),
    ]
